export const ActionName = {
  GET_CATEGORIES_PENDING: "GET_CATEGORIES_PENDING",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILED: "GET_CATEGORIES_FAILED",
};

export const BaseURL = "http://localhost:6200";
