export const ActionName = {
  GET_CATEGORIES_PENDING: "GET_CATEGORIES_PENDING",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILED: "GET_CATEGORIES_FAILED",
  GET_SUB_CATEGORIES_PENDING: "GET_SUB_CATEGORIES_PENDING",
  GET_SUB_CATEGORIES_SUCCESS: "GET_SUB_CATEGORIES_SUCCESS",
  GET_SUB_CATEGORIES_FAILED: "GET_SUB_CATEGORIES_FAILED",
  GET_PRODUCTS_PENDING: "GET_PRODUCTS_PENDING",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILED: "GET_PRODUCTS_FAILED",
};

export const BaseURL = "http://localhost:6200";
